###
POST http://localhost:4004/catalog/AttributiOggetto
Content-Type: application/json

{"ID": 1, "attribute_desc":"ID Company"}

###
POST http://localhost:4004/catalog/TipoOggetti
Content-Type: application/json

{"objType": "C02", "description":"Company", "attribute_ID":1}

###
GET http://localhost:4004/catalog/TipoOggetti?$expand=attribute
Content-Type: application/json

###
DELETE   http://localhost:4004/catalog/ObjectType
Content-Type: application/json
{"objtype": "COM"}
###
POST http://localhost:4004/catalog/ControlTypes
Content-Type: application/json

{"CtrlType": 1, "input":true, "selection": false, "searchHelp":false}